name: ci

on: pull_request
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Repo download
              uses: actions/checkout@v4

            - name: Python Install
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install Poetry
              run: |
                curl -sSL https://install.python-poetry.org | python -
                echo "${HOME}/.local/bin" >> $GITHUB_PATH

            - name: Install dependencies
              run: poetry install  

            - name: Libs Install
              run: pip install -r requirements.txt

            - name: rodar minha rotina de testes
              run: pytest tests/test_contrato.py 
              run: pytest tests/test_functional.py 