name: ci

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: first step
        run: echo "Hello, ${{ github.actor }}."

      - name: show the files in the current directory
        run: echo "The files in this directory are $(ls)."

      - name: what repository is this?
        run: echo "This is ${{ github.repository }}."
