name: ci

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      
      - name: install dependencies
        run: |
          poetry install
          poetry run pre-commit install

      - name: run tests
        run: |
          poetry run pytest
          poetry run pre-commit